### ISSUE TITLE
[TEST] Error: spawn [...] ipfs ENOENT

### ISSUE THREAD

**Issue by lazaridiscom** [trufflesuite/truffle-core#107]
## Issue

On **Win10** with **node 8.9.3**, the test `successfully installs single dependency from EthPM` fails.

This should be related to this issue:

ipfs/js-ipfs-api/issues/623

## Steps to Reproduce

```shell
cd  truffle-core
npm test
```

## Error

```
  Error: events.js:183
        throw er; // Unhandled 'error' event
        ^

  Error: spawn P:\sand\truffle\dependencies\truffle-core\node_modules\ipfsd-ctl\node_modules\go-ipfs-dep\go-ipfs\ipfs ENOENT
      at _errnoException (util.js:1024:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
      at onErrorNT (internal/child_process.js:372:16)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
      at startup (bootstrap_node.js:187:16)
      at bootstrap_node.js:608:3

      at Object.done (node_modules\ipfsd-ctl\src\exec.js:23:27)
      at Stream.listeners.done.once (node_modules\ipfsd-ctl\src\exec.js:45:18)
      at Stream.f (node_modules\once\once.js:25:25)
      at Socket.reemit (node_modules\duplexer\index.js:70:25)
      at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by lazaridiscom** [comment]
## Workaround

* Get the ipfs.exe from https://dist.ipfs.io/#go-ipfs
* manually create the directory-structure `ipfsd-ctl\node_modules\go-ipfs-dep\go-ipfs\`
* copy `ipfs.exe` there and rename it to `ipfs`
