### ISSUE TITLE
Error when running my fork of truffle-core: can't find module truffle-core/run?

### ISSUE THREAD

**Issue by roschler** [trufflesuite/truffle-core#147]
I'm trying to make my own custom build of the truffle-core repo.  I've forked the repo and made a Node.JS configuration in IntelliJ's WebStorm IDE.  When I run "npm start" I get the following exception:

```js
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/home/robert/Documents/GitHub/ME/truffle-core/run'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
Waiting for the debugger to disconnect...
```
What do I need to do to get a runnable/debuggable environment using this repo?

**Comment by roschler** [comment]
Got past that error.  I needed to specify `index.j` as my starting Javascript file.  Now I'm having a problem with it finding "./lib/config":

```js
Debugger attached.
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module './lib/config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/robert/Documents/GitHub/ME/truffle-core/index.js:6:11)
    at Module._compile (internal/modules/cjs/loader.js:699:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
Waiting for the debugger to disconnect...

Process finished with exit code 1
```
